name: Test packages

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'
      - name: Install dependencies
        run: |
          pip install -r dev-requirements.txt
      - name: Typechecking
        run: |
          mypy zeropdk
          pyright
      - name: Test with pytest
        run: |
          pytest -s